/*
 * This Scala source file was auto generated by running 'gradle buildInit --type scala-library'
 * by 'alexc' at '1/11/16 15:56' with Gradle 3.1
 *
 * @author alexc, @date 1/11/16 15:56
 */
class Library {
  def someLibraryMethod(): Boolean = true
}
