language: java
dist: trusty

jdk:
  - oraclejdk8
  - openjdk8

before_install:
 - chmod +x gradlew
 - sudo apt-get install jq
 - wget -O ~/codacy-coverage-reporter-assembly-latest.jar $(curl https://api.github.com/repos/codacy/codacy-coverage-reporter/releases/latest | jq -r .assets[0].browser_download_url)

after_success:

 - java -cp ~/codacy-coverage-reporter-assembly-latest.jar com.codacy.CodacyCoverageReporter -l Java -r build/reports/jacoco/test/jacocoTestReport.xml --projectToken d1fc8ab746d64890abcba26fa565f0bd
