/*
 * This Scala Testsuite was auto generated by running 'gradle init --type scala-library'
 * by 'alexc' at '1/11/16 15:56' with Gradle 3.1
 *
 * @author alexc, @date 1/11/16 15:56
 */

import org.scalatest.FunSuite
import org.junit.runner.RunWith
import org.scalatest.junit.JUnitRunner

@RunWith(classOf[JUnitRunner])
class LibrarySuite extends FunSuite {
  test("someLibraryMethod is always true") {
    def library = new Library()
    assert(library.someLibraryMethod)
  }
}
